"""
test_conformance_rng_pool.py — spec 53 §9-A gate test.

Loads tests/conformance/golden_vectors.json (generated by gen_golden.c
from the real C substrate) and asserts that the Python kernel in
core/systems/determinism reproduces EVERY field exactly.

A single-value mismatch fails the test and names the divergent field.
This is THE gate — until this passes, cross-device determinism is a claim.

Do not hand-edit golden_vectors.json. Regenerate via gen_golden.c if
rng.c or pool.c change (see tests/conformance/README.md).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from core.systems.determinism.rng import Rng, rng_seed, rng_next, rng_range, rng_chunk_seed
from core.systems.determinism.pool import (
    Pool,
    pool_at_prime,
    pool_at,
    pool_step,
    POOL_DIR_EAST,
    POOL_DIR_WEST,
    POOL_DIR_SOUTH,
    POOL_DIR_NORTH,
)

# ── Fixture ───────────────────────────────────────────────────────────────────

GOLDEN_PATH = Path(__file__).parent / "conformance" / "golden_vectors.json"


@pytest.fixture(scope="module")
def gv() -> dict:
    """Load golden vectors once for the entire module."""
    with GOLDEN_PATH.open() as f:
        return json.load(f)


# ── RNG: sequences ────────────────────────────────────────────────────────────

class TestRngSequences:
    """rng.sequences — 6 seeds × 20 rng_next calls."""

    def test_state_after_seed(self, gv: dict) -> None:
        """state_after_seed must reflect 0→1 promotion and non-zero identity."""
        for case in gv["rng"]["sequences"]:
            r = Rng()
            rng_seed(r, case["seed_arg"])
            expected = case["state_after_seed"]
            assert r.state == expected, (
                f"seed_arg={case['seed_arg']}: state_after_seed {r.state} != {expected}"
            )

    def test_next_20_values(self, gv: dict) -> None:
        """Each of the 20 rng_next outputs must match exactly."""
        for case in gv["rng"]["sequences"]:
            r = Rng()
            rng_seed(r, case["seed_arg"])
            for i, expected_val in enumerate(case["next_20"]):
                got = rng_next(r)
                assert got == expected_val, (
                    f"seed_arg={case['seed_arg']} call #{i + 1}: "
                    f"rng_next()={got} != {expected_val}"
                )

    def test_state_after_next_20(self, gv: dict) -> None:
        """State after 20 calls must equal the 20th output (xorshift: state IS the output)."""
        for case in gv["rng"]["sequences"]:
            r = Rng()
            rng_seed(r, case["seed_arg"])
            for _ in case["next_20"]:
                rng_next(r)
            expected = case["state_after_next_20"]
            assert r.state == expected, (
                f"seed_arg={case['seed_arg']}: state_after_20={r.state} != {expected}"
            )

    def test_seed_0_and_1_produce_identical_sequences(self, gv: dict) -> None:
        """Seed 0 must be promoted to 1 — the two sequences must be identical."""
        seqs = {c["seed_arg"]: c["next_20"] for c in gv["rng"]["sequences"]}
        assert seqs[0] == seqs[1], "Seed 0 and seed 1 produce different sequences"


# ── RNG: range cases ──────────────────────────────────────────────────────────

class TestRngRangeCases:
    """rng.range_cases — 9 cases covering span=1, degenerate hi<=lo, rejection."""

    def test_result_and_state_after(self, gv: dict) -> None:
        """Both result AND state_after must match (state_after catches rejection-count divergence)."""
        for case in gv["rng"]["range_cases"]:
            r = Rng()
            rng_seed(r, case["seed"])
            result = rng_range(r, case["lo"], case["hi"])
            assert result == case["result"], (
                f"seed={case['seed']} lo={case['lo']} hi={case['hi']}: "
                f"result={result} != {case['result']}"
            )
            assert r.state == case["state_after"], (
                f"seed={case['seed']} lo={case['lo']} hi={case['hi']}: "
                f"state_after={r.state} != {case['state_after']} "
                f"(rejection count diverged — check (0x100000000-span)%span formula)"
            )

    def test_rejection_fires_for_known_case(self, gv: dict) -> None:
        """
        seed=0xAAAAAAAA, span=0xC0000000 MUST fire rejection (consumes 2 rng_next calls).
        If reject collapsed to 0 (Python signed-modulo bug), state_after diverges here.
        This is the fast discriminator for the rejection-formula trap.
        """
        target_seed = 0xAAAAAAAA
        target_hi = 0xC0000000
        for case in gv["rng"]["range_cases"]:
            if case["seed"] == target_seed and case["hi"] == target_hi:
                r = Rng()
                rng_seed(r, target_seed)
                # Track calls manually to verify rejection fired
                call_count = [0]
                original_next = rng_next

                r2 = Rng()
                rng_seed(r2, target_seed)
                # Count via manual call — seed the two separately and compare states
                r_manual = Rng()
                rng_seed(r_manual, target_seed)
                v1 = rng_next(r_manual)
                v2 = rng_next(r_manual)
                # Rejection fires when the first value is below the threshold;
                # verify that the golden state_after equals state after exactly 2 calls
                assert r_manual.state == case["state_after"], (
                    f"Rejection case: state after 2 calls={r_manual.state} != "
                    f"{case['state_after']} — rejection may not have fired"
                )
                return
        pytest.fail("Rejection test case (seed=0xAAAAAAAA, hi=0xC0000000) not found in golden vectors")


# ── RNG: chunk seed ───────────────────────────────────────────────────────────

class TestRngChunkSeedCases:
    """rng.chunk_seed_cases — 8 cases including all four coordinate quadrants."""

    def test_all_cases(self, gv: dict) -> None:
        for case in gv["rng"]["chunk_seed_cases"]:
            got = rng_chunk_seed(case["base"], case["cx"], case["cy"])
            assert got == case["result"], (
                f"base={case['base']} cx={case['cx']} cy={case['cy']}: "
                f"result={got} != {case['result']}"
            )

    def test_all_quadrants_covered(self, gv: dict) -> None:
        """Ensure the vector set covers all four coordinate quadrants."""
        cases = gv["rng"]["chunk_seed_cases"]
        pos_x = any(c["cx"] > 0 for c in cases)
        neg_x = any(c["cx"] < 0 for c in cases)
        pos_y = any(c["cy"] > 0 for c in cases)
        neg_y = any(c["cy"] < 0 for c in cases)
        assert pos_x and neg_x and pos_y and neg_y, (
            "golden_vectors.json missing coordinate quadrant coverage"
        )

    def test_zero_base_returns_one(self, gv: dict) -> None:
        """base=0, cx=0, cy=0 must produce 1 (nonzero guarantee)."""
        for case in gv["rng"]["chunk_seed_cases"]:
            if case["base"] == 0 and case["cx"] == 0 and case["cy"] == 0:
                assert case["result"] == 1
                got = rng_chunk_seed(0, 0, 0)
                assert got == 1
                return


# ── Pool helpers ──────────────────────────────────────────────────────────────

_DIR_MAP = {
    "EAST": POOL_DIR_EAST,
    "WEST": POOL_DIR_WEST,
    "SOUTH": POOL_DIR_SOUTH,
    "NORTH": POOL_DIR_NORTH,
}


def _assert_pool_eq(got: Pool, expected: dict, label: str) -> None:
    """Compare every field of a Pool against a golden JSON object. Fails on first divergence."""
    assert got.theme_weights == expected["theme_weights"], (
        f"{label}: theme_weights {got.theme_weights} != {expected['theme_weights']}"
    )
    # primitive_bag: JSON has list of [id, weight] pairs
    for i, (bag_got, bag_exp) in enumerate(zip(got.primitive_bag, expected["primitive_bag"])):
        assert bag_got[0] == bag_exp[0] and bag_got[1] == bag_exp[1], (
            f"{label}: primitive_bag[{i}] {bag_got} != {bag_exp}"
        )
    assert got.family_bias == expected["family_bias"], (
        f"{label}: family_bias {got.family_bias} != {expected['family_bias']}"
    )
    assert got.loot_kind_bias == expected["loot_kind_bias"], (
        f"{label}: loot_kind_bias {got.loot_kind_bias} != {expected['loot_kind_bias']}"
    )
    assert got.intensity == expected["intensity"], (
        f"{label}: intensity {got.intensity} != {expected['intensity']}"
    )
    assert got.rotation_bias == expected["rotation_bias"], (
        f"{label}: rotation_bias {got.rotation_bias} != {expected['rotation_bias']}"
    )
    assert got.pedigree == expected["pedigree"], (
        f"{label}: pedigree {got.pedigree} != {expected['pedigree']}"
    )
    assert got.last_drop_slot == expected["last_drop_slot"], (
        f"{label}: last_drop_slot {got.last_drop_slot} != {expected['last_drop_slot']}"
    )


# ── Pool: at_prime ────────────────────────────────────────────────────────────

class TestPoolAtPrime:
    """pool.at_prime — 6 (prime_seed, biome) pairs."""

    def test_all_cases(self, gv: dict) -> None:
        for case in gv["pool"]["at_prime"]:
            got = pool_at_prime(case["prime_seed"], case["biome"])
            label = f"at_prime prime_seed={case['prime_seed']} biome={case['biome']}"
            _assert_pool_eq(got, case["pool"], label)

    def test_last_drop_slot_is_0xff_at_prime(self, gv: dict) -> None:
        """last_drop_slot must be 255 at prime for every case (spec 50 addendum §F1.A.4)."""
        for case in gv["pool"]["at_prime"]:
            got = pool_at_prime(case["prime_seed"], case["biome"])
            assert got.last_drop_slot == 0xFF, (
                f"at_prime prime_seed={case['prime_seed']} biome={case['biome']}: "
                f"last_drop_slot={got.last_drop_slot} != 255"
            )

    def test_intensity_zero_at_prime(self, gv: dict) -> None:
        for case in gv["pool"]["at_prime"]:
            got = pool_at_prime(case["prime_seed"], case["biome"])
            assert got.intensity == 0
            assert got.rotation_bias == 0


# ── Pool: at_xy ───────────────────────────────────────────────────────────────

class TestPoolAtXY:
    """pool.at_xy — 6 (prime_seed, biome, chunk_x, chunk_y) cases including negative coords."""

    def test_all_cases(self, gv: dict) -> None:
        for case in gv["pool"]["at_xy"]:
            got = pool_at(case["prime_seed"], case["biome"], case["chunk_x"], case["chunk_y"])
            label = (
                f"at_xy prime_seed={case['prime_seed']} biome={case['biome']} "
                f"x={case['chunk_x']} y={case['chunk_y']}"
            )
            _assert_pool_eq(got, case["pool"], label)

    def test_origin_matches_prime(self, gv: dict) -> None:
        """pool_at(…, 0, 0) must equal pool_at_prime(…)."""
        for case in gv["pool"]["at_xy"]:
            if case["chunk_x"] == 0 and case["chunk_y"] == 0:
                got_at = pool_at(case["prime_seed"], case["biome"], 0, 0)
                got_prime = pool_at_prime(case["prime_seed"], case["biome"])
                assert got_at.pedigree == got_prime.pedigree, (
                    f"pool_at(…,0,0).pedigree != pool_at_prime.pedigree"
                )


# ── Pool: step_sequences ──────────────────────────────────────────────────────

class TestPoolStepSequences:
    """pool.step_sequences — verify each individual step transition, not just the end state."""

    def test_all_step_transitions(self, gv: dict) -> None:
        for seq in gv["pool"]["step_sequences"]:
            prime_seed = seq["prime_seed"]
            biome = seq["biome"]
            p = pool_at_prime(prime_seed, biome)
            for step_case in seq["steps"]:
                step_n = step_case["step"]
                dir_int = step_case["dir_int"]
                pool_step(p, prime_seed, dir_int)
                label = (
                    f"step_seq prime_seed={prime_seed} biome={biome} "
                    f"step={step_n} dir={step_case['dir']}({dir_int})"
                )
                _assert_pool_eq(p, step_case["pool"], label)

    def test_direction_encoding(self, gv: dict) -> None:
        """dir_int in JSON must match the Python POOL_DIR_* constants."""
        for seq in gv["pool"]["step_sequences"]:
            for step_case in seq["steps"]:
                assert _DIR_MAP[step_case["dir"]] == step_case["dir_int"], (
                    f"Direction encoding mismatch: {step_case['dir']}={step_case['dir_int']} "
                    f"but POOL_DIR_{step_case['dir']}={_DIR_MAP[step_case['dir']]}"
                )
