import random
from dataclasses import dataclass


@dataclass
class ScoutResult:
    success: bool
    description: str
    aegis_delta: float
    xp_gain: int
    heat_gain: int  # Tracks the thermal surge generated by the mission


class ScoutEngine:
    def __init__(self, environmental_data: dict, player_snapshot: dict, heat: int = 0):
        self.env = environmental_data
        self.player = player_snapshot
        self.heat = heat  # Current thermal load passed from the database

    def resolve(self) -> ScoutResult:
        # 1. Base Hazard Rating (H)
        # Bad weather increases the baseline noise for the signal.
        hazard_rating = 40.0
        condition = self.env.get("condition", "Clear")
        if condition in ["Rain", "Snow", "Extreme", "Overcast"]:
            hazard_rating += 15.0

        # 2. Thermal Drag
        # Every point of heat adds to the difficulty.
        # Heat acts as a direct penalty to the success threshold.
        thermal_drag = self.heat / 2.0
        final_hazard = hazard_rating + thermal_drag

        # 3. Player Power
        # High Aegis provides better hardware/buffers, helping mitigate hazard.
        power_score = min(self.player.get("aegis", 0) / 1000, 30.0)

        # 4. The Resolution Roll
        # We roll 1-100 and add power. Must beat the Final Hazard.
        roll = random.randint(1, 100) + power_score
        success = roll >= final_hazard

        # 5. Outcome Calculation
        if success:
            delta = 100.0
            # Dynamic XP: Higher Hazard = Higher Reward
            # This ensures test_hazard_rating_calculation passes (e.g., 18 XP vs 24 XP)
            xp_reward = int(10 + (final_hazard / 5))

            # Successes generate moderate heat (5-12%)
            heat_generated = random.randint(5, 12)
            msg = f"Uplink stable in {self.env.get('city', 'Unknown')}. Fragments secured despite {self.heat}% thermal load."
        else:
            delta = -50.0
            xp_reward = 2  # Failures grant minimal "learning" XP

            # Failures generate significant heat (15-25%) due to signal retries
            heat_generated = random.randint(15, 25)
            msg = f"Signal lost. Thermal surge detected: {condition} interference too high."

        return ScoutResult(
            success=success,
            description=msg,
            aegis_delta=delta,
            xp_gain=xp_reward,
            heat_gain=heat_generated,
        )
